spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:src/main/datasource/SQLite
    username:
    password:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: 100
        max-idle: 8
        min-idle: 0


  mail:
    protocol: smtp #mail protocol
    host: SMTP.126.com
    username: jiayixxx@126.com #sending from
    password: TWTNJLSBHTXLAABR
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          port: 465
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
        debug: true #turn on debug
      smtp:
        ssl.enable: true

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 8880



